### ISSUE TITLE
Decide which alternative we should progress for Data Movement

### ISSUE THREAD

**Issue by davidgp1701** [DITAS-Project/data-movement-enactor#1]
In Haifa Meeting we decided about three diferent ideas for movement. We need to select one by March 15th.

**Comment by PavlovGrigor** [comment]
@eppages, due to different reasons and many discussions we will decide/present the alternative of Data Movement until 30th of April. It will be organized a call for that reason. Please provide access to Rene, Sergey and Peter for our github account.
